version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
      - image: circleci/postgres:9.6-alpine
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=kraal_test
          - JUNIT_DIR=~/junit
    working_directory: ~/kraal
    steps:
      - checkout
      - run: mkdir -p ~/junit
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
